//! Minimal example plugin (`step14.md`) proving the pipeline end-to-end:
//! `initialize` logs a greeting via the `log` host function, `on-event`
//! logs which event it received, `shutdown` logs a goodbye. No commands,
//! no UI, no capabilities requested -- deliberately the smallest thing
//! that proves load -> lifecycle -> host-function-calls -> resource
//! limits all work for real.
//!
//! Built with `cargo component build` (`step14.md` Decision 2) from this
//! directory; the resulting `target/wasm32-.../hello.wasm` is what
//! `PluginHostManager` (`crates/plugin-host`) discovers and instantiates.
//!
//! Bindings come from `mod bindings` below, generated by `cargo-component`
//! itself from `[package.metadata.component]`'s `target.path`/`target.world`
//! in `Cargo.toml` (pointed at the same `crates/plugin-sdk/wit/plugin-sdk.wit`
//! the host uses) -- **not** from depending on `crates/plugin-sdk` as a
//! library. A real finding from wiring this up: `cargo-component` always
//! generates its own bindings per-crate when `[package.metadata.component]`
//! is present, so `plugin-sdk`'s own `wit_bindgen::generate!`-produced
//! `Guest`/`export!` (`crates/plugin-sdk/src/lib.rs`) are never actually
//! reachable from a `cargo-component`-built guest -- confirmed by a real
//! `E0603: macro `export` is private` error when this crate first tried
//! `plugin_sdk::export!(...)`. `plugin-sdk` remains useful as the crate that
//! type-checked the WIT contract early (`step14.md` Implementation Notes)
//! and as the future home of a real `PluginCapability`-consuming manifest
//! helper, but it is not a build dependency of `cargo-component`-built
//! plugins.

#[allow(warnings)]
mod bindings;

use bindings::workspace::plugins::host_services;
use bindings::Guest;

struct HelloPlugin;

impl Guest for HelloPlugin {
    fn initialize(config: String) -> Result<(), String> {
        host_services::log(
            "info",
            &format!("hello plugin initialized (config: {config:?})"),
        );
        Ok(())
    }

    fn on_event(event_type: String, _payload: String) -> Result<(), String> {
        host_services::log(
            "info",
            &format!("hello plugin received event: {event_type}"),
        );
        Ok(())
    }

    fn shutdown() -> Result<(), String> {
        host_services::log("info", "hello plugin shutting down, goodbye!");
        Ok(())
    }
}

bindings::export!(HelloPlugin with_types_in bindings);
